#!/bin/bash


make

echo ""
echo "-- C O M P I L A T I O N -------------------------"

for i in {1..9}
do 
    echo ""
    echo "core00$i.lat:"
    ./latc_llvm ./lattests/good/core00$i.lat
done

for i in {10..28} 31 32
do 
    echo ""
    echo "core0$i.lat:"
    ./latc_llvm ./lattests/good/core0$i.lat
done



echo ""
echo "-- E X E C U T I O N -----------------------------"

for i in {1..9}
do 
    echo ""
    echo "core00$i.lat:"
    echo "-- OUTPUT ------------------------------------"
    lli ./lattests/good/core00$i.bc
    echo "-- EXPECTED ----------------------------------"
    cat ./lattests/good/core00$i.output
done

for i in {10..28} 31 32
do 
    echo ""
    echo "core0$i.lat:"
    echo "-- OUTPUT ------------------------------------"
    lli ./lattests/good/core0$i.bc
    echo "-- EXPECTED ----------------------------------"
    cat ./lattests/good/core0$i.output

done

make clean

