#!/bin/bash


make

echo ""
echo "-- C O M P I L A T I O N -------------------------"

for file in ./lattests/good/*.lat
do
    echo ""
    filename="$(basename $file .lat)" 
    echo "$filename.lat"
    ./latc_llvm $file
done


echo ""
echo "-- E X E C U T I O N -----------------------------"

for file in ./lattests/good/*.lat
do 
    echo ""
    dir="$(dirname $file)"
    filename="$(basename $file .lat)"
    llfile="$dir/$filename.ll"
    input="$dir/$filename.input"

    echo "$filename.lat"
    
    echo "-- OUTPUT ------------------------------------"
    if test -f $input
    then
        cat $input | lli $llfile
    else
        lli $llfile
    fi
    echo "-- EXPECTED ----------------------------------"
    cat $file.output
done


make clean

