#!/bin/bash


make

echo ""
echo "-- C O M P I L A T I O N -------------------------"

for file in ./lattests/good/*.lat
do
    echo ""
    dir="$(dirname $file)"
    filename="$(basename $file .lat)" 
    echo "$filename.lat"
    ./latc_llvm $file
    
    llvm-link -o "$dir/$filename.bc" "$dir/$filename.ll" runtime.ll
done


echo ""
echo "-- E X E C U T I O N -----------------------------"

for file in ./lattests/good/*.lat
do 
    echo ""
    dir="$(dirname $file)"
    filename="$(basename $file .lat)"
    execfile="$dir/$filename.bc"
    input="$dir/$filename.input"

    echo "$filename.lat"
    
    echo "-- OUTPUT ------------------------------------"
    if test -f $input
    then
        cat $input | lli $execfile
    else
        lli $execfile
    fi
    echo "-- EXPECTED ----------------------------------"
    cat $file.output
done


make clean

