#!/bin/bash


rm ./lattests/*/*.ll
rm ./lattests/*/*.bc
rm ./lattests/*/*.out

rm ./lattests/extensions/*/*.ll
rm ./lattests/extensions/*/*.bc
rm ./lattests/extensions/*/*.out

rm ./mrjp-tests/*/*.ll
rm ./mrjp-tests/*/*.bc
rm ./mrjp-tests/*/*.out

rm ./mrjp-tests/*/*/*.ll
rm ./mrjp-tests/*/*/*.bc
rm ./mrjp-tests/*/*/*.out

