#!/bin/bash


compile () {
    
    dir="$(dirname $1)"
    filename="$(basename $1 .lat)" 

    echo "$filename.lat"
    ./latc_llvm $1
}

execute () {

    dir="$(dirname $1)"
    filename="$(basename $1 .lat)"
    execfile="$dir/$filename.bc"
    input="$dir/$filename.input"
    expected_output="$dir/$filename.output"
    output_dir="$dir/$filename.out"

    echo ""
    echo "$filename.lat"
    
    if test -f $output_dir
    then
        rm $output_dir
    fi
    
    if test -f $input
    then
        (cat $input | lli $execfile) >> $output_dir
    else
        lli $execfile >> $output_dir
    fi
    python3 scripts/compare.py $output_dir $expected_output
}

make

echo ""
echo "-- C O M P I L A T I O N -------------------------"


echo ""
echo "-- ARRAYS ----------------------------------------"
for file in ./lattests/extensions/arrays1/*.lat
do
    compile $file
done

echo ""
echo "-- STRUCTS ---------------------------------------"
for file in ./lattests/extensions/struct/*.lat
do
    compile $file
done

echo ""
echo "-- OBJECTS1 --------------------------------------"
for file in ./lattests/extensions/objects1/*.lat
do
    compile $file
done

echo ""
echo "-- OBJECTS2 --------------------------------------"
for file in ./lattests/extensions/objects2/*.lat
do
    compile $file
done


echo ""
echo "-- E X E C U T I O N -----------------------------"



echo ""
echo "-- ARRAYS ----------------------------------------"
for file in ./lattests/extensions/arrays1/*.lat
do 
    execute $file

done

echo ""
echo "-- STRUCTS ---------------------------------------"
for file in ./lattests/extensions/struct/*.lat
do
    execute $file
done

echo ""
echo "-- OBJECTS1 --------------------------------------"
for file in ./lattests/extensions/objects1/*.lat
do
    filename="$(basename $file .lat)" 

    execute $file
done

echo "-- OBJECTS2 --------------------------------------"
for file in ./lattests/extensions/objects2/*.lat
do
    execute $file
done

make clean
./scripts/cleanup_tests
